name: Rodar batida de ponto

on:
  schedule:
    - cron: "0 11 * * 1-5"  # 08h BRT
    - cron: "0 14 * * 1-5"  # 11h BRT
    - cron: "0 16 * * 1-5"  # 13h BRT
    - cron: "0 20 * * 1-5"  # 17h BRT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar script
        run: python batida_ponto.py
